export const requirements = [
  {
    requirement_id: "1",
    buyer_id: "user123",
    product_title: "Cement Bags",
    categories: ["Construction", "Materials"],
    description: "Looking for high-quality cement bags in bulk.",
    quantity_needed: "500",
    price_range: "300-350",
    city: "Delhi",
    state: "Delhi",
    delivery_location: "Delhi NCR",
    created_at: "2025-09-01T10:00:00Z",
    updated_at: "2025-09-01T10:00:00Z",
  },
  {
    requirement_id: "2",
    buyer_id: "user456",
    product_title: "Office Chairs",
    categories: ["Furniture","Interior"],
    description: "Ergonomic chairs required for new office.",
    quantity_needed: "50",
    price_range: "2000-3000",
    city: "Mumbai",
    state: "Maharashtra",
    delivery_location: "Bandra",
    created_at: "2025-09-05T14:00:00Z",
    updated_at: "2025-09-05T14:00:00Z",
  },
];
